### ISSUE TITLE
Ignore dependencies by name or by their type (devDependencies, etc.)

### ISSUE THREAD

**Issue by leodido** [listendev/lstn#210]
### Describe the feature or problem you’d like to solve

We need a preemptive filtering mechanism/engine to not query the APIs about some dependencies.

### Proposed solution

Create 2 (configuration) flags:

```
--ignore-deptypes
--ignore-packages
```

Implement those only for `lstn scan` at the moment.

Also, ensure those are configurable via **config file**:

```yaml
...
filtering:
  ignore:
    packages:
      - "donotprocessme"
      - "react"
    deptypes:
     - "peer"
```

Finally, ensure those are configurable via **env vars**:

```
LSTN_IGNORE_DEPTYPES=peer,optional
LSTN_IGNORE_PACKAGES=react,@vue/devtools
```

### Additional context

This relates to #169 in that such a mechanism happens **before** analysing the dependencies.
